fint:
  org-id: fintlabs.no
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    application-id: fint-skjema-configuration-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-skjema-configuration-service
  data:
    mongodb:
      database: skjema-configuration
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
server:
  port: 8080
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs.cache: WARN
    org:
      springframework:
        security: DEBUG