fint:
  org-id: fintlabs.no
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    application-id: fint-flyt-configuration-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-skjema-configuration-service
  datasource:
    hikari:
      schema: fintlabs_no
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fint-flyt-configuration-service
    username: postgres
    password: password
  jpa:
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: __init.sql
#              create-source: metadata
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  flyway:
    locations: classpath:db/migration/
server:
  port: 8080
  max-http-header-size: 40KB

